name:                hjq
version:             0.1.0.0
github:              "githubuser/hjq"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hjq#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- attoparsec
- bytestring
- errors
- lens
- lens-aeson
- text
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  hjq:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hjq
    - aeson
    - aeson-pretty
    - attoparsec
    - bytestring
    - errors
    - lens
    - lens-aeson
    - text
    - unordered-containers
    - vector

tests:
  hjq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hjq
    - HUnit
    - aeson
    - lens
    - lens-aeson
    - text
